"""delivery phase 2 initial schema

Creates the five tables Delivery Phase 2 introduces:

    plants                     the plant a submission belongs to
    rule_sets                  which rules were in force, by content digest
    mdr_submissions            one uploaded workbook and its lifecycle
    mdr_document_rows          the processed rows and their four automation
                               columns
    mdr_processing_summaries   one run's counts, pointing at its rule set

Autogenerated against `app.infrastructure.persistence.models` and left as
generated apart from this docstring - so the migration and the models cannot
have drifted at the moment it was written, and
`tests/persistence/test_migrations.py` asserts they still have not.

`downgrade` drops all five. That is a real reversal on an empty schedule and a
data-destroying one on a populated database; it exists so a migration can be
stepped back during development, not as a production rollback plan.

Revision ID: 0001
Revises:
Create Date: 2026-09-09 16:38:48.292042

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plants')),
    sa.UniqueConstraint('code', name=op.f('uq_plants_code'))
    )
    op.create_table('rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('required_rule_count', sa.Integer(), nullable=False),
    sa.Column('not_required_rule_count', sa.Integer(), nullable=False),
    sa.Column('sow_rule_count', sa.Integer(), nullable=False),
    sa.Column('idb_rules_origin', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(content_sha256) = 64', name=op.f('ck_rule_sets_content_sha256_is_a_digest')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_sets')),
    sa.UniqueConstraint('content_sha256', name=op.f('uq_rule_sets_content_sha256')),
    sa.UniqueConstraint('version_label', name=op.f('uq_rule_sets_version_label'))
    )
    op.create_table('mdr_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('submission_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_byte_size', sa.BigInteger(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('source_sheet_name', sa.Text(), nullable=True),
    sa.Column('source_header_row', sa.Integer(), nullable=True),
    sa.Column('source_row_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('automated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UPLOADED', 'EXTRACTED', 'AUTOMATED', 'FAILED')", name=op.f('ck_mdr_submissions_status_is_known')),
    sa.CheckConstraint('length(source_sha256) = 64', name=op.f('ck_mdr_submissions_source_sha256_is_a_digest')),
    sa.CheckConstraint('source_byte_size > 0', name=op.f('ck_mdr_submissions_source_byte_size_is_positive')),
    sa.CheckConstraint('submission_no > 0', name=op.f('ck_mdr_submissions_submission_no_is_positive')),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], name=op.f('fk_mdr_submissions_plant_id_plants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mdr_submissions')),
    sa.UniqueConstraint('plant_id', 'submission_no', name='uq_mdr_submissions_plant_id_submission_no')
    )
    op.create_index('ix_mdr_submissions_plant_id_uploaded_at', 'mdr_submissions', ['plant_id', 'uploaded_at'], unique=False)
    op.create_index('ix_mdr_submissions_source_sha256', 'mdr_submissions', ['source_sha256'], unique=False)
    op.create_index('ix_mdr_submissions_status', 'mdr_submissions', ['status'], unique=False)
    op.create_table('mdr_document_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('document_identity', sa.Text(), nullable=False),
    sa.Column('qatarenergy_document_no', sa.Text(), nullable=False),
    sa.Column('revision', sa.String(length=32), nullable=False),
    sa.Column('revision_raw', sa.String(length=64), nullable=False),
    sa.Column('revision_status', sa.String(length=32), nullable=False),
    sa.Column('is_latest_revision', sa.Boolean(), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=False),
    sa.Column('discipline', sa.Text(), nullable=False),
    sa.Column('doc_with_rev', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('sow', sa.Text(), nullable=False),
    sa.Column('idb_completed_status', sa.Text(), nullable=False),
    sa.Column('check_status', sa.Text(), nullable=False),
    sa.Column('doc_type_rule', sa.Text(), nullable=False),
    sa.Column('sow_source', sa.Text(), nullable=False),
    sa.Column('idb_source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_status = ''", name=op.f('ck_mdr_document_rows_check_status_not_evaluated')),
    sa.CheckConstraint('source_row > 0', name=op.f('ck_mdr_document_rows_source_row_is_positive')),
    sa.ForeignKeyConstraint(['submission_id'], ['mdr_submissions.id'], name=op.f('fk_mdr_document_rows_submission_id_mdr_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mdr_document_rows')),
    sa.UniqueConstraint('submission_id', 'source_row', name='uq_mdr_document_rows_submission_id_source_row')
    )
    op.create_index('ix_mdr_document_rows_submission_id_doc_type', 'mdr_document_rows', ['submission_id', 'doc_type'], unique=False)
    op.create_index('ix_mdr_document_rows_submission_id_document_identity', 'mdr_document_rows', ['submission_id', 'document_identity'], unique=False)
    op.create_table('mdr_processing_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('doc_with_rev_populated', sa.Integer(), nullable=False),
    sa.Column('doc_type_populated', sa.Integer(), nullable=False),
    sa.Column('sow_populated', sa.Integer(), nullable=False),
    sa.Column('sow_unresolved', sa.Integer(), nullable=False),
    sa.Column('idb_populated', sa.Integer(), nullable=False),
    sa.Column('idb_unmapped', sa.Integer(), nullable=False),
    sa.Column('idb_manual_check_required', sa.Integer(), nullable=False),
    sa.Column('check_status_populated', sa.Integer(), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_status_populated = 0', name=op.f('ck_mdr_processing_summaries_check_status_never_populated')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_mdr_processing_summaries_row_count_is_not_negative')),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], name=op.f('fk_mdr_processing_summaries_rule_set_id_rule_sets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['mdr_submissions.id'], name=op.f('fk_mdr_processing_summaries_submission_id_mdr_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mdr_processing_summaries')),
    sa.UniqueConstraint('submission_id', name='uq_mdr_processing_summaries_submission_id')
    )
    op.create_index('ix_mdr_processing_summaries_rule_set_id', 'mdr_processing_summaries', ['rule_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mdr_processing_summaries_rule_set_id', table_name='mdr_processing_summaries')
    op.drop_table('mdr_processing_summaries')
    op.drop_index('ix_mdr_document_rows_submission_id_document_identity', table_name='mdr_document_rows')
    op.drop_index('ix_mdr_document_rows_submission_id_doc_type', table_name='mdr_document_rows')
    op.drop_table('mdr_document_rows')
    op.drop_index('ix_mdr_submissions_status', table_name='mdr_submissions')
    op.drop_index('ix_mdr_submissions_source_sha256', table_name='mdr_submissions')
    op.drop_index('ix_mdr_submissions_plant_id_uploaded_at', table_name='mdr_submissions')
    op.drop_table('mdr_submissions')
    op.drop_table('rule_sets')
    op.drop_table('plants')
    # ### end Alembic commands ###
